name: flutter_ffi_grpc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.0
  grpc: ^4.1.0
  protobuf: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  provider: ^6.0.0
  ini: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/config.ini
